//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DellyShopApp.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DellyShopApp.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Details.
        /// </summary>
        internal static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Address.
        /// </summary>
        internal static string AddAddress {
            get {
                return ResourceManager.GetString("AddAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basket.
        /// </summary>
        internal static string AddBasket {
            get {
                return ResourceManager.GetString("AddBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add child.
        /// </summary>
        internal static string AddChild {
            get {
                return ResourceManager.GetString("AddChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Credit Card.
        /// </summary>
        internal static string AddCreditCard {
            get {
                return ResourceManager.GetString("AddCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product has been added to your basket..
        /// </summary>
        internal static string AddedBakset {
            get {
                return ResourceManager.GetString("AddedBakset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Money.
        /// </summary>
        internal static string AddMoney {
            get {
                return ResourceManager.GetString("AddMoney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Address.
        /// </summary>
        internal static string AddNewAddress {
            get {
                return ResourceManager.GetString("AddNewAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Card.
        /// </summary>
        internal static string AddNewCard {
            get {
                return ResourceManager.GetString("AddNewCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Detail.
        /// </summary>
        internal static string AddressDetail {
            get {
                return ResourceManager.GetString("AddressDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Title.
        /// </summary>
        internal static string AddressTitle {
            get {
                return ResourceManager.GetString("AddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed Products.
        /// </summary>
        internal static string AllowedProducts {
            get {
                return ResourceManager.GetString("AllowedProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Rights Reserved To 2020 Masrofee.
        /// </summary>
        internal static string ARR {
            get {
                return ResourceManager.GetString("ARR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string Balance {
            get {
                return ResourceManager.GetString("Balance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Seller.
        /// </summary>
        internal static string BestSeller {
            get {
                return ResourceManager.GetString("BestSeller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday.
        /// </summary>
        internal static string Birthday {
            get {
                return ResourceManager.GetString("Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calories.
        /// </summary>
        internal static string Calories {
            get {
                return ResourceManager.GetString("Calories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen Products.
        /// </summary>
        internal static string CanteenProducts {
            get {
                return ResourceManager.GetString("CanteenProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canteen Status.
        /// </summary>
        internal static string CanteenStatus {
            get {
                return ResourceManager.GetString("CanteenStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        internal static string CardName {
            get {
                return ResourceManager.GetString("CardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Children Details.
        /// </summary>
        internal static string ChildrenDetails {
            get {
                return ResourceManager.GetString("ChildrenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Childrens.
        /// </summary>
        internal static string Childrens {
            get {
                return ResourceManager.GetString("Childrens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New York.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clothing.
        /// </summary>
        internal static string Clothing {
            get {
                return ResourceManager.GetString("Clothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commented on 5.
        /// </summary>
        internal static string Commented {
            get {
                return ResourceManager.GetString("Commented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete Order.
        /// </summary>
        internal static string CompleteOrder {
            get {
                return ResourceManager.GetString("CompleteOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Confirm.
        /// </summary>
        internal static string ConfirmPass {
            get {
                return ResourceManager.GetString("ConfirmPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United State.
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily limit.
        /// </summary>
        internal static string Dailylimit {
            get {
                return ResourceManager.GetString("Dailylimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme Enabled.
        /// </summary>
        internal static string DarkThemeEnabled {
            get {
                return ResourceManager.GetString("DarkThemeEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Daily limit.
        /// </summary>
        internal static string EditDailylimit {
            get {
                return ResourceManager.GetString("EditDailylimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        internal static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electronics.
        /// </summary>
        internal static string Electronics {
            get {
                return ResourceManager.GetString("Electronics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Notification.
        /// </summary>
        internal static string EnableNotification {
            get {
                return ResourceManager.GetString("EnableNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        internal static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount.
        /// </summary>
        internal static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email address..
        /// </summary>
        internal static string EnterEmailAddress {
            get {
                return ResourceManager.GetString("EnterEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        internal static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        internal static string EnterPhone {
            get {
                return ResourceManager.GetString("EnterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username or email.
        /// </summary>
        internal static string EnterUserOrEmail {
            get {
                return ResourceManager.GetString("EnterUserOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Example &apos;Home Address&apos;.
        /// </summary>
        internal static string ExampleHomeAddress {
            get {
                return ResourceManager.GetString("ExampleHomeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiration.
        /// </summary>
        internal static string Expiration {
            get {
                return ResourceManager.GetString("Expiration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        internal static string ForgotPass {
            get {
                return ResourceManager.GetString("ForgotPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password? .
        /// </summary>
        internal static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter The Mobile Number And You Will Receive SMS to Recover Your Password..
        /// </summary>
        internal static string ForgotPasswordDetails {
            get {
                return ResourceManager.GetString("ForgotPasswordDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter full name.
        /// </summary>
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get New One.
        /// </summary>
        internal static string GetNewOne {
            get {
                return ResourceManager.GetString("GetNewOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        internal static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactive.
        /// </summary>
        internal static string Inactive {
            get {
                return ResourceManager.GetString("Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last.
        /// </summary>
        internal static string Last {
            get {
                return ResourceManager.GetString("Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last View.
        /// </summary>
        internal static string LastView {
            get {
                return ResourceManager.GetString("LastView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Summary.
        /// </summary>
        internal static string LoadSummary {
            get {
                return ResourceManager.GetString("LoadSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Simple Summary.
        /// </summary>
        internal static string LoadSummarySimple {
            get {
                return ResourceManager.GetString("LoadSummarySimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        internal static string LoremComment {
            get {
                return ResourceManager.GetString("LoremComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string LoremIpsum {
            get {
                return ResourceManager.GetString("LoremIpsum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maqsafi number.
        /// </summary>
        internal static string MaqsafiNumber {
            get {
                return ResourceManager.GetString("MaqsafiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Masroofi number.
        /// </summary>
        internal static string MasroofiNumber {
            get {
                return ResourceManager.GetString("MasroofiNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Amount Per Day.
        /// </summary>
        internal static string MaxAmountPerDay {
            get {
                return ResourceManager.GetString("MaxAmountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Amount Per Day.
        /// </summary>
        internal static string MaximumAmountPerDay {
            get {
                return ResourceManager.GetString("MaximumAmountPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Basket.
        /// </summary>
        internal static string MyBasket {
            get {
                return ResourceManager.GetString("MyBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Comments.
        /// </summary>
        internal static string MyComments {
            get {
                return ResourceManager.GetString("MyComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Favorites.
        /// </summary>
        internal static string MyFavorites {
            get {
                return ResourceManager.GetString("MyFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Orders.
        /// </summary>
        internal static string MyOrders {
            get {
                return ResourceManager.GetString("MyOrders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        internal static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National / iqama ID.
        /// </summary>
        internal static string NationalID {
            get {
                return ResourceManager.GetString("NationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have account? .
        /// </summary>
        internal static string NoAccount {
            get {
                return ResourceManager.GetString("NoAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no financial operations.
        /// </summary>
        internal static string NoFinancialOperations {
            get {
                return ResourceManager.GetString("NoFinancialOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was no results.
        /// </summary>
        internal static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Big discount on electrical products.
        /// </summary>
        internal static string NotificatinTitle {
            get {
                return ResourceManager.GetString("NotificatinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Detail.
        /// </summary>
        internal static string NotificationDetail {
            get {
                return ResourceManager.GetString("NotificationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discounts up to 50%.
        /// </summary>
        internal static string NotificationSubtitle {
            get {
                return ResourceManager.GetString("NotificationSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Okay.
        /// </summary>
        internal static string Okay {
            get {
                return ResourceManager.GetString("Okay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date :.
        /// </summary>
        internal static string OrderDate {
            get {
                return ResourceManager.GetString("OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order No :.
        /// </summary>
        internal static string OrderNo {
            get {
                return ResourceManager.GetString("OrderNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Status :.
        /// </summary>
        internal static string OrderStatus {
            get {
                return ResourceManager.GetString("OrderStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing Stage.
        /// </summary>
        internal static string PackingStage {
            get {
                return ResourceManager.GetString("PackingStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture.
        /// </summary>
        internal static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Viewed.
        /// </summary>
        internal static string PreviousViewed {
            get {
                return ResourceManager.GetString("PreviousViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Men&apos;s Nike Air Max 270 Casual.
        /// </summary>
        internal static string ProcutTitle {
            get {
                return ResourceManager.GetString("ProcutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grey Firozi Mesh.
        /// </summary>
        internal static string ProcutTitle1 {
            get {
                return ResourceManager.GetString("ProcutTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presto Yellow.
        /// </summary>
        internal static string ProcutTitle2 {
            get {
                return ResourceManager.GetString("ProcutTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iPhone 8 Plus Gold.
        /// </summary>
        internal static string ProcutTitle3 {
            get {
                return ResourceManager.GetString("ProcutTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nike.
        /// </summary>
        internal static string ProductBrand {
            get {
                return ResourceManager.GetString("ProductBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ASIAN.
        /// </summary>
        internal static string ProductBrand1 {
            get {
                return ResourceManager.GetString("ProductBrand1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nike.
        /// </summary>
        internal static string ProductBrand2 {
            get {
                return ResourceManager.GetString("ProductBrand2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apple.
        /// </summary>
        internal static string ProductBrand3 {
            get {
                return ResourceManager.GetString("ProductBrand3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Shoes are for regular comfort wear. The body of this shoe is in a neutral grey colour with light blue accents. The upper material keeps air circulation while moderated ankles take full care of your feet when you go out for running....
        /// </summary>
        internal static string ProductDesc {
            get {
                return ResourceManager.GetString("ProductDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Detail.
        /// </summary>
        internal static string ProductDetail {
            get {
                return ResourceManager.GetString("ProductDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        internal static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAR.
        /// </summary>
        internal static string SAR {
            get {
                return ResourceManager.GetString("SAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search List.
        /// </summary>
        internal static string SearchList {
            get {
                return ResourceManager.GetString("SearchList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Address.
        /// </summary>
        internal static string SelectAddress {
            get {
                return ResourceManager.GetString("SelectAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select City.
        /// </summary>
        internal static string SelectCity {
            get {
                return ResourceManager.GetString("SelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Country.
        /// </summary>
        internal static string SelectCountry {
            get {
                return ResourceManager.GetString("SelectCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Credit Card.
        /// </summary>
        internal static string SelectCreditCard {
            get {
                return ResourceManager.GetString("SelectCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select School.
        /// </summary>
        internal static string SelectSchool {
            get {
                return ResourceManager.GetString("SelectSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Street.
        /// </summary>
        internal static string SelectStreet {
            get {
                return ResourceManager.GetString("SelectStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select week day.
        /// </summary>
        internal static string SelectWeekDay {
            get {
                return ResourceManager.GetString("SelectWeekDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Balance.
        /// </summary>
        internal static string SendBalance {
            get {
                return ResourceManager.GetString("SendBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Comment.
        /// </summary>
        internal static string SendComment {
            get {
                return ResourceManager.GetString("SendComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Cost.
        /// </summary>
        internal static string ShippingCost {
            get {
                return ResourceManager.GetString("ShippingCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shoes.
        /// </summary>
        internal static string Shoes {
            get {
                return ResourceManager.GetString("Shoes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodmax Canteens System.
        /// </summary>
        internal static string Shop {
            get {
                return ResourceManager.GetString("Shop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show More Detail.
        /// </summary>
        internal static string ShowMoreDetail {
            get {
                return ResourceManager.GetString("ShowMoreDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıgn ın.
        /// </summary>
        internal static string Signin {
            get {
                return ResourceManager.GetString("Signin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sıgn up.
        /// </summary>
        internal static string Signup {
            get {
                return ResourceManager.GetString("Signup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Son&apos;s Purchases.
        /// </summary>
        internal static string SonsPurchases {
            get {
                return ResourceManager.GetString("SonsPurchases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Type :.
        /// </summary>
        internal static string SortType {
            get {
                return ResourceManager.GetString("SortType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broadway.
        /// </summary>
        internal static string StreetName {
            get {
                return ResourceManager.GetString("StreetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        internal static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        internal static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Order!.
        /// </summary>
        internal static string SuccessOrder {
            get {
                return ResourceManager.GetString("SuccessOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password renewal mail has been sent to your email address..
        /// </summary>
        internal static string SuccessSendEmail {
            get {
                return ResourceManager.GetString("SuccessSendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary End Date.
        /// </summary>
        internal static string SummaryEndDate {
            get {
                return ResourceManager.GetString("SummaryEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary Start Date.
        /// </summary>
        internal static string SummaryStartDate {
            get {
                return ResourceManager.GetString("SummaryStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string TandC {
            get {
                return ResourceManager.GetString("TandC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to MASROFEE
        ///
        ///This Privacy Policy sets out the basis on which any personal data, including but not limited to payment details and other information we collect from you or other sources or that you provide to us (&quot;Information&quot;) will be handled by us in connection with your access and use of masrofee app, and/or the Masrofee mobile application (collectively, the &quot;Platform&quot;), services and applications (collectively, the &quot;Services&quot;). We understand the importance you place on the Information, and we are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TermsAndCond {
            get {
                return ResourceManager.GetString("TermsAndCond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With millions of products at your service.
        /// </summary>
        internal static string TitleDesc {
            get {
                return ResourceManager.GetString("TitleDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s Report.
        /// </summary>
        internal static string TodaysReport {
            get {
                return ResourceManager.GetString("TodaysReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todays spent.
        /// </summary>
        internal static string TodaysSpent {
            get {
                return ResourceManager.GetString("TodaysSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top up.
        /// </summary>
        internal static string Topup {
            get {
                return ResourceManager.GetString("Topup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Credit.
        /// </summary>
        internal static string TotalCredit {
            get {
                return ResourceManager.GetString("TotalCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Current Balance.
        /// </summary>
        internal static string TotalCurrentBalance {
            get {
                return ResourceManager.GetString("TotalCurrentBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Debit.
        /// </summary>
        internal static string TotalDebit {
            get {
                return ResourceManager.GetString("TotalDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price:.
        /// </summary>
        internal static string TotalPrice {
            get {
                return ResourceManager.GetString("TotalPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total spent.
        /// </summary>
        internal static string TotalSpent {
            get {
                return ResourceManager.GetString("TotalSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions Summary.
        /// </summary>
        internal static string TransactionsSummary {
            get {
                return ResourceManager.GetString("TransactionsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View All.
        /// </summary>
        internal static string ViewAll {
            get {
                return ResourceManager.GetString("ViewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Weekly Plan.
        /// </summary>
        internal static string ViewWeeklyPlan {
            get {
                return ResourceManager.GetString("ViewWeeklyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Plan.
        /// </summary>
        internal static string WeeklyPlan {
            get {
                return ResourceManager.GetString("WeeklyPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Comment.
        /// </summary>
        internal static string YourComment {
            get {
                return ResourceManager.GetString("YourComment", resourceCulture);
            }
        }
    }
}
